---

# Variables here are applicable to all host groups
deploy_user: "{{ ansible_user }}"
status_dir: "{{ deploy_dir }}/status"
backup_dir: "{{ deploy_dir }}/backup"
images_dir: "{{ deploy_dir }}/images"

# Local
downloads_dir: "{{ playbook_dir }}/downloads"
script_dir:    "{{ playbook_dir }}/scripts"

# Random shifts for retrying failed ops like downloading
retry_stagger: 5

# Zookeeper Server