---
- name: set zookeeper package
  set_fact:
    zookeeper_server_bin: "apache-zookeeper-{{ zookeeper_version }}-bin"
    zookeeper_server_pkg: "apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"

- name: checking {{ zookeeper_server_pkg }} exists
  stat:
    path: "{{ zookeeper_root_dir }}/{{ zookeeper_server_pkg }}"
  register: zookeeper_server_pkg_data

- name: checking {{ zookeeper_server_bin }} exists
  stat:
    path: "{{ zookeeper_root_dir }}/{{ zookeeper_server_bin }}"
  register: zookeeper_server_bin_data

- name: copy local package to remote
  copy: src="{{ item.src }}" dest="{{ item.dest }}" mode=0755
  with_items:
    - {src: "{{ downloads_dir }}/{{ zookeeper_server_pkg }}", dest: "{{ zookeeper_root_dir }}"}
  when: not zookeeper_server_pkg_data.stat.exists

- name: unarchive zookeeper pkg
  unarchive: src="{{ zookeeper_root_dir }}/{{ zookeeper_server_pkg }}" dest="{{ zookeeper_root_dir }}/"
  when: not zookeeper_server_bin_data.stat.exists

- name: create zookeeper myid file.
  template: src="myid.j2" dest="{{ zookeeper_data_dir }}/myid" mode=0644

- name: create zookeeper configuration file.
  template: src="zoo.cfg.j2" dest="{{ zookeeper_conf_dir }}/zoo.cfg" mode=0644

- name: create zookeeper log4j configuration file.
  template: src="log4j.properties.j2" dest="{{ zookeeper_conf_dir }}/log4j.properties" mode=0644

- name: install open jdk
  yum:
    name: java-1.8.0-openjdk
    state: present
  become: true
