---
- name: Set zookeeper package
  set_fact:
    zookeeper_pkg: "apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"

- name: Download zookeeper package
  get_url:
    url: "https://mirrors.tuna.tsinghua.edu.cn/apache/zookeeper/zookeeper-{{ zookeeper_pkg }}/"
    dest: "{{ zookeeper_root_dir }}/{{ zookeeper_pkg }}"
    force: yes
    validate_certs: no
  register: get_url_result
  until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
  retries: 4
  delay: "{{ retry_stagger | random + 3 }}"
