---
# Author: dusen.me@gmail.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# See the License for the specific language governing permissions and
# limitations under the License.

# The playbook of zookeeper

- name: check config locally
  hosts: localhost
  any_errors_fatal: true
  tags:
    - always
  roles:
    - check_config_static

- name: starting zookeeper server cluster
  hosts: zookeeper_servers
  tags:
    - zookeeper_server
  tasks:
    - name: stop zookeeper server first
      shell: "{{ zookeeper_bin_dir }}/zkServer.sh stop"
      args:
        warn: false
      ignore_errors: yes 
      become: true

    - name: check if zookeeper client port already in use
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ zookeeper_client_port }}"
        state: stopped
        timeout: 3
        msg: "{{ zookeeper_client_port }} already in use"

    - name: check if zookeeper admin port already in use
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ zookeeper_admin_port }}"
        state: stopped
        timeout: 3
        msg: "{{ zookeeper_admin_port }} already in use"

    - name: start zookeeper server
      shell: "{{ zookeeper_bin_dir }}/zkServer.sh start"
      become: true

    - name: wait until the zookeeper client port is up
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ zookeeper_client_port }}"
        state: started
        msg: "the zookeeper client port {{ zookeeper_client_port }} is not up"

    - name: wait until the zookeeper admin port is up
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ zookeeper_admin_port }}"
        state: started
        msg: "the zookeeper client port {{ zookeeper_admin_port }} is not up"
