---
# Author: dusen.me@gmail.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# See the License for the specific language governing permissions and
# limitations under the License.

# The playbook of ClickHouse

- hosts: localhost
  tasks:
    - name: confirm operation
      pause:
        prompt: "The operation will clear the cluster and the data will be deleted (Ctrl-c C or enter to continue, Ctrl-c A to Abort)"

- import_playbook: stop.yml

- hosts: clickhouse_servers
  tasks:
    - name: remove clickhouse package.
      yum:
        name: 
          - clickhouse-common-static
          - clickhouse-common
          - "{{ clickhouse_server_name }}"
          - clickhouse-client
        state: absent
      become: true

    - name: remove clickhouse config and data.
      shell: |
        bash -c 'rm -rf /etc/{{ clickhouse_server_name }}'
        bash -c 'rm -rf {{ clickhouse_data_dir }}'
      args:
        warn: false
      ignore_errors: yes 
      become: true

- import_playbook: stop_zk.yml

- hosts: zookeeper_servers
  tasks:
    - name: remove zookeeper package and binary.
      shell: |
        bash -c 'rm -rf {{ clickhouse_data_dir }}'
        bash -c 'rm -rf {{ clickhouse_data_dir }}'
      args:
        warn: false
      ignore_errors: yes 
      become: true
