---

# CPU
clickhouse_min_cpu: 8
clickhouse_replica_min_cpu: 8

# Mem
clickhouse_min_ram: 16000
clickhouse_replica_min_ram: 16000

# Disk
clickhouse_min_disk: 500000000000
clickhouse_replica_min_disk: 500000000000
