---
- name: set clickhouse package name
  set_fact:
    clickhouse_common_pkg: "clickhouse_common-{{ clickhouse_version }}.rpm"
    clickhouse_server_pkg: "clickhouse_server-{{ clickhouse_version }}.rpm"

- name: copy local package to remote
  copy: src="{{ item.src }}" dest="{{ item.dest }}" mode=0755
  with_items:
    - {src: "{{ downloads_dir }}/{{ clickhouse_common_pkg }}", dest: "{{ clickhouse_root_dir }}"}
    - {src: "{{ downloads_dir }}/{{ clickhouse_server_pkg }}", dest: "{{ clickhouse_root_dir }}"}

- name: remove clickhouse package.
  yum:
    name: 
      - clickhouse-common-static
      - clickhouse-common
      - clickhouse-server
      - clickhouse*
    state: absent
  become: true

- name: install clickhouse common package.
  shell: rpm -ivh "{{ clickhouse_root_dir }}/{{ clickhouse_common_pkg }}"
  args:
    warn: false
  become: true

- name: install clickhouse server package.
  shell: rpm -ivh "{{ clickhouse_root_dir }}/{{ clickhouse_server_pkg }}"
  args:
    warn: false
  become: true

- name: create clickhouse directory
  file:
    path: "{{ item }}"
    owner: clickhouse 
    group: clickhouse 
    mode: 0755
    state: directory
  with_items:
    - "/etc/{{ clickhouse_server_name }}"
    - "/etc/{{ clickhouse_server_name }}/config.d"
    - "/etc/{{ clickhouse_server_name }}/users.d"
    - "{{ clickhouse_root_dir }}/clickhouse"
    - "{{ clickhouse_root_dir }}/clickhouse/data"
    - "{{ clickhouse_root_dir }}/clickhouse/log"

- name: create clickhouse configuration file.
  template: src="config.xml.j2" dest="/etc/{{ clickhouse_server_name }}/config.xml" mode=0644

- name: create clickhouse users file.
  template: src="users.xml.j2" dest="/etc/{{ clickhouse_server_name }}/users.xml" mode=0644

- name: create clickhouse metrika file.
  template: src="metrika.xml.j2" dest="/etc/{{ clickhouse_server_name }}/metrika.xml" mode=0644
