---
- name: set clickhouse package name
  set_fact:
    clickhouse_common_pkg: "clickhouse_common-{{ clickhouse_version }}.rpm"
    clickhouse_client_pkg: "clickhouse_client-{{ clickhouse_version }}.rpm"

- name: copy local package to remote
  copy: src="{{ item.src }}" dest="{{ item.dest }}" mode=0755
  with_items:
    - {src: "{{ downloads_dir }}/{{ clickhouse_common_pkg }}", dest: "{{ clickhouse_root_dir }}"}
    - {src: "{{ downloads_dir }}/{{ clickhouse_client_pkg }}", dest: "{{ clickhouse_root_dir }}"}

- name: remove clickhouse package.
  yum:
    name: 
      - clickhouse-common-static
      - clickhouse-common
      - clickhouse-client
      - clickhouse*
    state: absent
  become: true

- name: install clickhouse common package.
  shell: rpm -ivh "{{ clickhouse_root_dir }}/{{ clickhouse_common_pkg }}"
  args:
    warn: false
  become: true

- name: install clickhouse client package.
  shell: rpm -ivh "{{ clickhouse_root_dir }}/{{ clickhouse_client_pkg }}"
  args:
    warn: false
  become: true
