---

- name: Debian/Ubuntu - install python
  shell: sudo apt-get -y install python python3
  when:
    - "'Ubuntu' in distro or 'Debian' in distro"
    - "not has_python"

- name: Redhat/CentOS - install python
  shell: sudo yum -y install python python3
  when:
    - "'CentOS' in distro"
    - "not has_python"
