---
- name: Set ClickHouse Replica package name
  set_fact:
    clickhouse_common_pkg_name: "clickhouse_common-{{ clickhouse_version }}.rpm"
    clickhouse_server_pkg_name: "clickhouse_server-{{ clickhouse_version }}.rpm"
    clickhouse_client_pkg_name: "clickhouse_client-{{ clickhouse_version }}.rpm"

# 因为副本和分片在同一台机器上，所以下面的安装步骤可以不用执行
# - name: Copy local package to remote
#   copy: src="{{ item.src }}" dest="{{ item.dest }}" mode=0755
#   with_items:
#     - {src: "{{ downloads_dir }}/{{ clickhouse_common_pkg_name }}", dest: "{{ clickhouse_replica_root_dir }}"}
#     - {src: "{{ downloads_dir }}/{{ clickhouse_server_pkg_name }}", dest: "{{ clickhouse_replica_root_dir }}"}
#     - {src: "{{ downloads_dir }}/{{ clickhouse_client_pkg_name }}", dest: "{{ clickhouse_replica_root_dir }}"}
#   sudo: yes

# - name: Remove ClickHouse Replica package.
#   yum:
#     name: 
#       - clickhouse-common-static
#       - clickhouse-common
#       - clickhouse-server
#       - clickhouse-client
#       - clickhouse*
#     state: absent
#   sudo: yes

# - name: Install ClickHouse Replica Common package.
#   shell: rpm -ivh "{{ clickhouse_replica_root_dir }}/{{ clickhouse_common_pkg_name }}"
#   args:
#     warn: false
#   sudo: yes

# - name: Install ClickHouse Replica Server package.
#   shell: rpm -ivh "{{ clickhouse_replica_root_dir }}/{{ clickhouse_server_pkg_name }}"
#   args:
#     warn: false
#   sudo: yes

# - name: Install ClickHouse Replica Client package.
#   shell: rpm -ivh "{{ clickhouse_replica_root_dir }}/{{ clickhouse_client_pkg_name }}"
#   args:
#     warn: false
#   sudo: yes

- name: Create ClickHouse Replica directory
  file:
    path: "{{ item }}"
    owner: clickhouse 
    group: clickhouse 
    mode: 0755
    state: directory
  with_items:
    - "/etc/{{ clickhouse_replica_server_name }}"
    - "/etc/{{ clickhouse_replica_server_name }}/config.d"
    - "/etc/{{ clickhouse_replica_server_name }}/users.d"
    - "{{ clickhouse_replica_root_dir }}/clickhouse"
    - "{{ clickhouse_replica_root_dir }}/clickhouse/data"
    - "{{ clickhouse_replica_root_dir }}/clickhouse/log"
  sudo: yes

- name: Create ClickHouse Replica configuration file.
  template: src="config.xml.j2" dest="/etc/{{ clickhouse_replica_server_name }}/config.xml" mode=0644
  sudo: yes

- name: Create ClickHouse Replica users file.
  template: src="users.xml.j2" dest="/etc/{{ clickhouse_replica_server_name }}/users.xml" mode=0644
  sudo: yes

- name: Create ClickHouse Replica metrika file.
  template: src="metrika.xml.j2" dest="/etc/{{ clickhouse_replica_server_name }}/metrika.xml" mode=0644
  sudo: yes

- name: Create ClickHouse Replica init.d file.
  template: src="init.d.j2" dest="/etc/init.d/{{ clickhouse_replica_server_name }}" mode=0755
  sudo: yes

- name: Create ClickHouse Replica cron.d file.
  template: src="cron.d.j2" dest="/etc/cron.d/{{ clickhouse_replica_server_name }}" mode=0644
  sudo: yes
